package wasi:graphics-context@0.2.0-rc.1;

world imports {
  import graphics-context;
}

interface graphics-context {
  resource context {
    constructor();

    get-current-buffer: func() -> abstract-buffer;

    // TODO: might want to remove this.
    present: func();
  }

  resource abstract-buffer { }
}
