package wasi:frame-buffer@0.2.0-rc.1;

world imports {
  import frame-buffer;
}

interface frame-buffer {
  use wasi:graphics-context/graphics-context@0.2.0-rc.1.{context, abstract-buffer};

  resource device {
    constructor();

    connect-graphics-context: func(context: borrow<context>);
  }

  resource buffer {
    from-graphics-buffer: static func(buffer: abstract-buffer) -> buffer;

    // TODO: This should be replcated with something that doesn't require a copy.
    get: func() -> list<u8>;
    set: func(val: list<u8>);
  }
}
