// TODO: Move this into mini-canvas.

package wasi:webgpu;

/// This is similar to requestAnimationFrame in JavaScript, or wl_surface::frame in Wayland.
/// Should update as fast as the users display can, but not faster.
interface animation-frame {
    use wasi:io/poll@0.2.0.{pollable};

    listener: func() -> frame-listener;

    resource frame-listener {
        subscribe: func() -> pollable;

        get: func() -> option<frame-event>;
    }

    record frame-event {
        /// This field doesn't mean anything.
        // Can't have empty record. Would like to have a way around this.
        nothing: bool,
    }
}
