package wasi:webgpu;

interface graphics-context {
    resource context {
        constructor();

        get-current-buffer: func() -> buffer;

        // TODO: might want to remove this.
        present: func();
    }

    resource buffer { }
}
