package wasi:webgpu;

// TODO: Move this into mini-canvas.

interface key-events {
    use wasi:io/poll@0.2.0.{pollable};
    use mini-canvas.{mini-canvas};

    up-listener: func(mini-canvas: borrow<mini-canvas>) -> key-up-listener;

    resource key-up-listener {
        subscribe: func() -> pollable;

        get: func() -> option<key-event>;
    }

    down-listener: func(mini-canvas: borrow<mini-canvas>) -> key-down-listener;

    resource key-down-listener {
        subscribe: func() -> pollable;

        get: func() -> option<key-event>;
    }

    record key-event {
        // should `code` and `key` be enums?
        code: string,
        key: string,
        alt-key: bool,
        ctrl-key: bool,
        meta-key: bool,
        shift-key: bool,
    }
}
