package wasi:webgpu;

// TODO: Move this into mini-canvas.

interface pointer-events {
    use wasi:io/poll@0.2.0.{pollable};
    use mini-canvas.{mini-canvas};

    up-listener: func(mini-canvas: borrow<mini-canvas>) -> pointer-up-listener;

    resource pointer-up-listener {
        subscribe: func() -> pollable;

        get: func() -> option<pointer-event>;
    }

    down-listener: func(mini-canvas: borrow<mini-canvas>) -> pointer-down-listener;

    resource pointer-down-listener {
        subscribe: func() -> pollable;

        get: func() -> option<pointer-event>;
    }

    move-listener: func(mini-canvas: borrow<mini-canvas>) -> pointer-move-listener;

    resource pointer-move-listener {
        subscribe: func() -> pollable;

        get: func() -> option<pointer-event>;
    }

    record pointer-event {
        x: f64,
        y: f64,
    }
}
