package wasi:webgpu;

world imports {
    import webgpu;
    import graphics-context;
    import mini-canvas;
    import animation-frame;
    import pointer-events;
    import key-events;
    import frame-buffer;
}
